version: "3.9"

services:
  content-analytics-service:
    build:
      context: ./services/content-analytics-service
    environment:
      - CONFIG_PATH=/app/configs/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2-20
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo_data: {}
