// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: legal_assistant.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Question request message
type QuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	K             int32                  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"` // Number of relevant documents to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionRequest) Reset() {
	*x = QuestionRequest{}
	mi := &file_legal_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionRequest) ProtoMessage() {}

func (x *QuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legal_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionRequest.ProtoReflect.Descriptor instead.
func (*QuestionRequest) Descriptor() ([]byte, []int) {
	return file_legal_assistant_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QuestionRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

// Response message for streaming answers
type QuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	References    []string               `protobuf:"bytes,2,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionResponse) Reset() {
	*x = QuestionResponse{}
	mi := &file_legal_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionResponse) ProtoMessage() {}

func (x *QuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legal_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionResponse.ProtoReflect.Descriptor instead.
func (*QuestionResponse) Descriptor() ([]byte, []int) {
	return file_legal_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *QuestionResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QuestionResponse) GetReferences() []string {
	if x != nil {
		return x.References
	}
	return nil
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_legal_assistant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legal_assistant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_legal_assistant_proto_rawDescGZIP(), []int{2}
}

// Health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     float64                `protobuf:"fixed64,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_legal_assistant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legal_assistant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_legal_assistant_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_legal_assistant_proto protoreflect.FileDescriptor

const file_legal_assistant_proto_rawDesc = "" +
	"\n" +
	"\x15legal_assistant.proto\x12\x0flegal_assistant\"5\n" +
	"\x0fQuestionRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\"F\n" +
	"\x10QuestionResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"references\x18\x02 \x03(\tR\n" +
	"references\"\x14\n" +
	"\x12HealthCheckRequest\"K\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x01R\ttimestamp2\xc4\x01\n" +
	"\x0eLegalAssistant\x12V\n" +
	"\vAskQuestion\x12 .legal_assistant.QuestionRequest\x1a!.legal_assistant.QuestionResponse\"\x000\x01\x12Z\n" +
	"\vHealthCheck\x12#.legal_assistant.HealthCheckRequest\x1a$.legal_assistant.HealthCheckResponse\"\x00B>Z<github.com/LAWGEN/lawgen-backend/chat-service/internal/pb;pbb\x06proto3"

var (
	file_legal_assistant_proto_rawDescOnce sync.Once
	file_legal_assistant_proto_rawDescData []byte
)

func file_legal_assistant_proto_rawDescGZIP() []byte {
	file_legal_assistant_proto_rawDescOnce.Do(func() {
		file_legal_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_legal_assistant_proto_rawDesc), len(file_legal_assistant_proto_rawDesc)))
	})
	return file_legal_assistant_proto_rawDescData
}

var file_legal_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_legal_assistant_proto_goTypes = []any{
	(*QuestionRequest)(nil),     // 0: legal_assistant.QuestionRequest
	(*QuestionResponse)(nil),    // 1: legal_assistant.QuestionResponse
	(*HealthCheckRequest)(nil),  // 2: legal_assistant.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: legal_assistant.HealthCheckResponse
}
var file_legal_assistant_proto_depIdxs = []int32{
	0, // 0: legal_assistant.LegalAssistant.AskQuestion:input_type -> legal_assistant.QuestionRequest
	2, // 1: legal_assistant.LegalAssistant.HealthCheck:input_type -> legal_assistant.HealthCheckRequest
	1, // 2: legal_assistant.LegalAssistant.AskQuestion:output_type -> legal_assistant.QuestionResponse
	3, // 3: legal_assistant.LegalAssistant.HealthCheck:output_type -> legal_assistant.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_legal_assistant_proto_init() }
func file_legal_assistant_proto_init() {
	if File_legal_assistant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_legal_assistant_proto_rawDesc), len(file_legal_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_legal_assistant_proto_goTypes,
		DependencyIndexes: file_legal_assistant_proto_depIdxs,
		MessageInfos:      file_legal_assistant_proto_msgTypes,
	}.Build()
	File_legal_assistant_proto = out.File
	file_legal_assistant_proto_goTypes = nil
	file_legal_assistant_proto_depIdxs = nil
}
