# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: legal_assistant.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'legal_assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15legal_assistant.proto\x12\x0flegal_assistant\"+\n\x0fQuestionRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\"4\n\x10QuestionResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nreferences\x18\x02 \x03(\t\"\x14\n\x12HealthCheckRequest\"8\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x32\xc4\x01\n\x0eLegalAssistant\x12V\n\x0b\x41skQuestion\x12 .legal_assistant.QuestionRequest\x1a!.legal_assistant.QuestionResponse\"\x00\x30\x01\x12Z\n\x0bHealthCheck\x12#.legal_assistant.HealthCheckRequest\x1a$.legal_assistant.HealthCheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'legal_assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTIONREQUEST']._serialized_start=42
  _globals['_QUESTIONREQUEST']._serialized_end=85
  _globals['_QUESTIONRESPONSE']._serialized_start=87
  _globals['_QUESTIONRESPONSE']._serialized_end=139
  _globals['_HEALTHCHECKREQUEST']._serialized_start=141
  _globals['_HEALTHCHECKREQUEST']._serialized_end=161
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=163
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=219
  _globals['_LEGALASSISTANT']._serialized_start=222
  _globals['_LEGALASSISTANT']._serialized_end=418
# @@protoc_insertion_point(module_scope)
