name: Build and Push FastAPI to ACR

on:
  push:
    branches:
      - ai-service  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: lawgenacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Ai-services  
        file: ./Ai-services/Dockerfile
        push: true
        tags: lawgenacr.azurecr.io/appsvc/staticsite:latest
