name: Build, Push to ACR, and Deploy to ACA

on:
  push:
    branches:
      - user-service

env:
  ACR_NAME: 'lawgenacr'
  MICROSERVICE_NAME: 'user-service'
  RESOURCE_GROUP: 'Zekua'
  CONTAINER_APP_ENV: 'lawgen'
  TARGET_PORT: '8080'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./user_management
          file: ./user_management/Dockerfile
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.MICROSERVICE_NAME }}:${{ github.sha }}
          build-args: |
            PORT=${{ env.TARGET_PORT }}
            ENV=${{ secrets.ENV }}

      - name: Deploy to Azure Container App using Azure CLI
        run: |
          az containerapp update \
            --name ${{ env.MICROSERVICE_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/${{ env.MICROSERVICE_NAME }}:${{ github.sha }} \
            --set-env-vars \
              PORT=${{ env.TARGET_PORT }} \
              ENV=${{ secrets.ENV }} \
              MONGODB_URI=${{ secrets.MONGODB_URI }} \
              MONGODB_DB=${{ secrets.MONGODB_DB }} \
              ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
              REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} \
              ACCESS_TOKEN_EXPIRY=${{ secrets.ACCESS_TOKEN_EXPIRY }} \
              REFRESH_TOKEN_EXPIRY=${{ secrets.REFRESH_TOKEN_EXPIRY }} \
              API_KEY=${{ secrets.API_KEY }} \
              API_SECRET=${{ secrets.API_SECRET }} \
              CLOUD_NAME=${{ secrets.CLOUD_NAME }} \
              SMTP_HOST=${{ secrets.SMTP_HOST }} \
              SMTP_PORT=${{ secrets.SMTP_PORT }} \
              SMTP_USER=${{ secrets.SMTP_USER }} \
              SMTP_PASS=${{ secrets.SMTP_PASS }} \
              FROM_EMAIL=${{ secrets.FROM_EMAIL }} \
              GEMINI_AI_API_KEY=${{ secrets.GEMINI_AI_API_KEY }} \
              GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }} \
              GOOGLE_OAUTH_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }} \
              OAUTH_STATE_STRING=${{ secrets.OAUTH_STATE_STRING }} \
              APP_URL=${{ secrets.URL }}
        shell: bash
